### PR TITLE
ci: build examples by dependency

### PR DESCRIPTION
**Pull request by trombik**
this PR build examples if, and only if, the examples are affected by PRs.

the PR is supposed to build:

* all `i2c` based examples when `i2c` component is modified by PRs
* all examples for `foo` component when `foo` component is modified by PRs
* all examples when the PR has `area:ci`

### CODE REVIEW

**Comment by UncleRus** [comment]
What is the purpose of the `yq` file in the root directory?

**Comment by trombik** [comment]
> What is the purpose of the `yq` file in the root directory?

it is there due to my fat finger. just removed from my branch. next push will remove it from the history,

**Comment by trombik** [comment]
the PR is ready to merge.

you can test the PR by

* removing `area:ci` and any `area:components:*`, then add `area:components:i2cdev` ("Build examples" should run, and all `i2c`-based components should be built)
* removing `area:ci` and any `area:components:*`, then add `area:components:mcp23x17` ("Build examples" should run, and only `mcp23x17` examples  should be built)
* removing `area:ci` and any `area:components:*`, then add `area:ci` ("Build examples" should run, and all examples should be built)

**Comment by UncleRus** [comment]
Awesome work, Sakurai-san!
Thank you.

**Pull request merged**
