### PR TITLE
hmc5983: added 220 Hz data rate option

### PR DESCRIPTION
**Pull request by dizcza**

### CODE REVIEW

**Comment by UncleRus** [comment]
Thank you! But this PR needs a little more work.

If the driver supports the new chip, then you need to do the following:

1. Specify the supported chip in the header comments of the driver (in both files, `hmc5883l.h` and hmc5883l.c``).
2. Add the supported chip to the driver metainformation (file eil.yml, "description" field).
3. Add chip info to docs files: `docs/source/groups/hmc5883l.rst` and `docs/source/chips.rst`
4. Generate a new version of the `README.md` file, see [CONTRIBUTING.md](https://github.com/UncleRus/esp-idf-lib/blob/master/CONTRIBUTING.md#updating-readmemd)

**Comment by dizcza** [comment]
It'd be nice if you explain here and in the contributing guideline steps to install build env.

I have no idea which package is meant to have the `bundle` command available on Linux.

**Comment by trombik** [comment]
i don't know which Linux distro you are using, but something below should work.

```console
apt-get install bundler
yum install rubygem-bundler
dnf install rubygem-bundler
```

or, if you already have ruby, 

```console
gem install bundler
```

**Comment by dizcza** [comment]
> gem install bundler

This is definitely not enough as I'm getting.
```
$ bundle exec rake -C devtools readme > README.md
bundler: failed to load command: rake (/usr/local/bin/rake)
Traceback (most recent call last):
	23: from /usr/bin/bundle:23:in `<main>'
	22: from /usr/bin/bundle:23:in `load'
	21: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/exe/bundle:36:in `<top (required)>'
	20: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
	19: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/exe/bundle:48:in `block in <top (required)>'
	18: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:25:in `start'
	17: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	16: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:31:in `dispatch'
	15: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	14: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	12: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli.rb:483:in `exec'
	11: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:23:in `run'
	10: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:56:in `kernel_load'
	 9: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/cli/exec.rb:56:in `require_relative'
	 8: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/setup.rb:20:in `<top (required)>'
	 7: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/ui/shell.rb:88:in `silence'
	 6: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/ui/shell.rb:136:in `with_level'
	 5: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/setup.rb:20:in `block in <top (required)>'
	 4: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler.rb:162:in `setup'
	 3: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/runtime.rb:18:in `setup'
	 2: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/definition.rb:247:in `specs_for'
	 1: from /var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/definition.rb:191:in `specs'
/var/lib/gems/2.7.0/gems/bundler-2.3.18/lib/bundler/definition.rb:498:in `materialize': Could not find irb-1.3.7, rspec-3.10.0, rubocop-1.22.3, reline-0.2.7, rspec-core-3.10.1, rspec-expectations-3.10.1, rspec-mocks-3.10.2, parallel-1.21.0, parser-3.0.2.0, rainbow-3.0.0, regexp_parser-2.1.1, rexml-3.2.5, rubocop-ast-1.13.0, ruby-progressbar-1.11.0, unicode-display_width-2.1.0, io-console-0.5.9, rspec-support-3.10.3, diff-lcs-1.4.4, ast-2.4.2 in any of the sources (Bundler::GemNotFound)
```

Neither does the apt package manager.

As I said, setting up a dev env documentation is missing.

**Comment by trombik** [comment]
although the order of the sections is wrong, but here is the documentation:

https://github.com/UncleRus/esp-idf-lib/blob/master/Metadata.md#readmemd
https://github.com/UncleRus/esp-idf-lib/blob/master/Metadata.md#validating-metadata-of-components

i'll update the `Metadata.md`.

**Comment by trombik** [comment]
run:

```console
bundle install
bundle exec rake -C devtools readme > README.md
```

**Comment by dizcza** [comment]
> run:
> 
> ```
> bundle install
> bundle exec rake -C devtools readme > README.md
> ```

So I did and the readme didn't change.

**Comment by trombik** [comment]
because you've already changed `README.md` by hand.

**Comment by dizcza** [comment]
Exactly. So it's ready to be merged.

**Comment by UncleRus** [comment]
@dizcza Thank you!

**Pull request merged**
