### PR TITLE
ci: introduce build_esp8266_v3_x, skip-duplicate-actions GitHub Actions

### PR DESCRIPTION
**Pull request by trombik**

### CODE REVIEW

**Comment by trombik** [comment]
@UncleRus when you create a feature branch in this repository (i.e. pushing a branch to the remote on GitHub), all jobs will run. when you create a PR from the feature branch, jobs will be skipped. when the PR is merged, jobs will be skipped. is this what you expect?

when someone create a feature branch in a forked repository, all jobs will run. when the user create a PR from the feature branch, all jobs will run because the test result in other repository is not part of `UncleRus/esp-idf-lib` repository. when you merge the PR, jobs will be skipped, _I guess_ (cannot confirmed yet).

not fully understand `skip-duplicate-actions` yet, but _I think_ this PR implements behaviors above.

**Comment by UncleRus** [comment]
@trombik Hi!
All I want is to just stop building twice when I pushing to a branch that already has a PR.
That is, when I fork the master into another branch, and then push into it, the CI starts - this is OK. But if I create a PR from this branch, then every time I push to this branch, the build is launched twice: for a push and for a pull request.

**Comment by trombik** [comment]
@UncleRus the PR implements half of your requirements. when you are working on a feature branch and when you create a PR from the feature branch, jobs run only once. jobs run twice when you push another commit to the branch of the PR. maybe i missed something in `skip-duplicate-actions`, or I need another hack.

**Comment by UncleRus** [comment]
> jobs run twice when you push another commit to the branch of the PR

This is exactly what I'm trying to aviod.

**Comment by trombik** [comment]
> > jobs run twice when you push another commit to the branch of the PR
> 
> This is exactly what I'm trying to aviod.

it should be fixed in the latest commit.

**Comment by UncleRus** [comment]
> > > jobs run twice when you push another commit to the branch of the PR
> > 
> > 
> > This is exactly what I'm trying to aviod.
> 
> it should be fixed in the latest commit.

Thank you!

**Pull request merged**
