### PR TITLE
Add driver for TSL2591.

### PR DESCRIPTION
**Pull request by juliandoerner**
Adds driver for the light-to-digital sensor TSL2591 from AMS.
This driver provides methods for the internal interrupts.

Support was requested by #145.

### CODE REVIEW

**Comment by juliandoerner** [comment]
Checks failed because I included two examples.
Should I move them one folder up like
../examples/tsl2591_simple
../examples/tsl2591_interrupts...
or should I delete one example?

**Comment by UncleRus** [comment]
All examples should be directly in the `/examples` directory. So yeah, you need to move them up.

**Comment by UncleRus** [comment]
Otherwise, the code looks great. Great contribution, thank you!

**Comment by UncleRus** [comment]
One more thing: modify main README.md: add new component to the table and don't forget to mention yourself in contributors list.
Also you need to add documentation section and modify `index.rst` accordingly.

**Comment by juliandoerner** [comment]
Apparently, I put some whitespace in the Makefile. The PR passes the CI now.
Thanks for this nice library!

**Pull request merged**
