### PR TITLE
feature: New devtool, simpler metadata, simpler CI

### PR DESCRIPTION
**Pull request by UncleRus**
WIP because job for ESP8266 is not ready.

### CODE REVIEW

**Comment by UncleRus** [comment]
More than 2 hours to build all examples! Looks like ccache is not working at all.
@igrr what am I doing wrong?

**Comment by UncleRus** [comment]
OK, ccache is working now. @igrr Sorry for bothering you, it was my fault :)

@trombik Why do you think labeler is constantly launched in this PR? I removed the relevant .yml files

**Comment by trombik** [comment]
The labeler runs because it's a special action to protect CI from third party. In short, it will run until the YAML file is removed from the master branch.

**Comment by UncleRus** [comment]
> The labeler runs because it's a special action to protect CI from third party. In short, it will run until the YAML file is removed from the master branch.

Wow! Didn't know it was possible.

I hope the new CI will not cause rejection in you. :)

**Comment by trombik** [comment]
i don't have time at the moment, will have a look later.

**Pull request merged**
