### PR TITLE
ci: document Personal Access Token for automation

### LINKED ISSUE #396: Document Personal Access Token and its usage in CI
### The issue

Personal Access Token is required in the new CI to automate labeling PRs, but its documentation is missing.

### The context

_No response_

### Possible solution

_No response_

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

### PR DESCRIPTION
**Pull request by trombik**
fixes #396

### CODE REVIEW

**Comment by trombik** [comment]
@UncleRus documented what is needed to activate the new workflow. please follow the steps.

https://github.com/UncleRus/esp-idf-lib/blob/88383d2fbab240257dff053b4ac3aea7e73d9f40/.github/workflows/README.md#the-triggering-labeler-workflow-and-personal-access-token

the new workflow is working, but will not automatically run without `LABELER_TOKEN`.

**Comment by UncleRus** [comment]
First, I don't understand where this token will be used. No, it's clear to me that it's needed to start label-based workflows. But let's say I generated it. What's next? Should it be listed somewhere? Where? How? Will this token only be used for PRs created by me or for everyone?
Secondly, it is absolutely unclear what rights for the token should be chosen. There is a huge list of items on the token generation page. What to choose?

The further, the more incomprehensible to me what is happening with the repository CI.

**Comment by UncleRus** [comment]
EDIT: OK, I read the text more carefully, and the first part of the questions has disappeared, I'm sorry. But I still don't understand what rights to the token should be given.

**Comment by trombik** [comment]
sorry, forgot to mention the required scope. fixed in 2a7f5bd853c1b268f27688e44c97267c08f05349.

**Comment by UncleRus** [comment]
Okay, I just created a token with the specified scope, and stored it in the repository secrets called by 'LABELER_TOKEN'

**Comment by UncleRus** [comment]
And CI doesn't works.
I created PR (#400) and just nothing, no checks at all.

**Comment by trombik** [comment]
you need to merge this PR first.

or, if you manually label the PR, th CI should run.

**Comment by UncleRus** [comment]
Thank you.
Immediately after adding the label, I received a message from github:

> [UncleRus/esp-idf-lib] Run failed at startup: Actions on PR by label - bugfix-warnings (4955122)
> изображение

**Comment by trombik** [comment]
I often forgot that GitHub doesn't like double quotes. will fix it.

https://github.com/UncleRus/esp-idf-lib/actions/runs/2577075779/workflow

**Pull request merged**
