### PR TITLE
Driver+example for AM2320 (I2C mode)

### LINKED ISSUE #454: Driver for am2320 using i2c
### Device name

am2320

### Device description

AM2320 is a temperature and humidity composite sensor with a calibrated digital signal output

### Device product page URL

http://www.aosong.com/en/products-41.html

### Datasheet URL

https://cdn-shop.adafruit.com/product-files/3721/AM2320.pdf

### Can the device be purchased at any of the followings?

- [X] AliExpress
- [ ] Amazon
- [ ] ebay
- [ ] Digi-Key
- [ ] Mouser

### URLs to purchase the device

https://aliexpress.com/item/32654739552.html?spm=a2g0o.productlist.0.0.59477cb0e9ifXo&algo_pvid=ecacd069-bea0-4953-8238-ccf3fb3de654&algo_exp_id=ecacd069-bea0-4953-8238-ccf3fb3de654-0
https://aliexpress.com/item/1005002884884196.html

### Other implementations

https://github.com/adafruit/Adafruit_AM2320
https://github.com/Ten04031977/AM2320-master/blob/master/am2320.cpp

### PR DESCRIPTION
**Pull request by UncleRus**
Fixes #454

@aschiavon91, @sirapol, @pfuentes69 Please test

### CODE REVIEW

**Comment by aschiavon91** [comment]
I got some errors.
```
I (274) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (281) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (287) heap_init: At 4008C8A8 len 00013758 (77 KiB): IRAM
I (294) spi_flash: detected chip: generic
I (298) spi_flash: flash io: dio
I (303) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (0) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4008637c
0x4008637c: _esp_error_check_failed at /home/aschiavon/esp/esp-idf/components/esp_system/esp_err.c:42

file: "/home/aschiavon/Projetos/IOT/esp32/hello_world/main/am2320_sensor.c" line 18
func: AM2320Read
expression: am2320_get_device_id(&dev, &dev_id)

abort() was called at PC 0x4008637f on core 1
0x4008637f: _esp_error_check_failed at /home/aschiavon/esp/esp-idf/components/esp_system/esp_err.c:43



Backtrace:0x40081426:0x3ffb81b00x40086389:0x3ffb81d0 0x4008b59a:0x3ffb81f0 0x4008637f:0x3ffb8260 0x400d27e7:0x3ffb8280 0x40088ee1:0x3ffb82f0
0x40081426: panic_abort at /home/aschiavon/esp/esp-idf/components/esp_system/panic.c:402

0x40086389: esp_system_abort at /home/aschiavon/esp/esp-idf/components/esp_system/esp_system.c:128

0x4008b59a: abort at /home/aschiavon/esp/esp-idf/components/newlib/abort.c:46

0x4008637f: _esp_error_check_failed at /home/aschiavon/esp/esp-idf/components/esp_system/esp_err.c:43

0x400d27e7: AM2320Read at /home/aschiavon/Projetos/IOT/esp32/hello_world/main/am2320_sensor.c:18 (discriminator 1)

0x40088ee1: vPortTaskWrapper at /home/aschiavon/esp/esp-idf/components/freertos/port/xtensa/port.c:131





ELF file SHA256: 785dea74c6c904c0

Rebooting...
```

**Comment by UncleRus** [comment]
Looks like a wiring problem.
Please recheck wiring, use appropriate pull-up resistors.

I also ask you to build and flash an I2C bus scanner into your device. 
https://github.com/UncleRus/esp-idf-lib/tree/master/examples/i2cdev/default

**Comment by aschiavon91** [comment]
> Looks like a wiring problem. Please recheck wiring, use appropriate pull-up resistors.
> 
> I also ask you to build and flash an I2C bus scanner into your device. https://github.com/UncleRus/esp-idf-lib/tree/master/examples/i2cdev/default

You're right, it's a wiring problem, after adding appropriate pull-up resistors I'm able to read the temp and humidity, but I'm also getting some errors, I did do something wrong?
```
I (10) am2320: Model ID:  131
I (10) am2320: Version:   0
I (20) am2320: Temperature: 30.5°C, Humidity: 51.8%
E (520) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (520) am2320: Error reading data: -1 (ESP_FAIL)
E (1030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (1030) am2320: Error reading data: -1 (ESP_FAIL)
I (1530) am2320: Temperature: 30.5°C, Humidity: 51.8%
E (2030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (2030) am2320: Error reading data: -1 (ESP_FAIL)
I (2530) am2320: Temperature: 30.5°C, Humidity: 51.8%
E (3030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (3030) am2320: Error reading data: -1 (ESP_FAIL)
I (3530) am2320: Temperature: 30.5°C, Humidity: 51.9%
E (4030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (4030) am2320: Error reading data: -1 (ESP_FAIL)
I (4530) am2320: Temperature: 30.5°C, Humidity: 51.9%
E (5030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (5030) am2320: Error reading data: -1 (ESP_FAIL)
I (5530) am2320: Temperature: 30.5°C, Humidity: 51.9%
E (6030) i2cdev: Could not write to device [0x5c at 0]: -1 (ESP_FAIL)
E (6030) am2320: Error reading data: -1 (ESP_FAIL)
```

**Comment by aschiavon91** [comment]
I have been testing since last comment, and besides those errors, the implementation seems to be working pretty well

**Comment by trombik** [comment]
@UncleRus will have a look

**Comment by trombik** [comment]
the datasheet is the one of the worst i have ever read.

**Comment by trombik** [comment]
@aschiavon91 please test the new example. there should be no warnings or errors.

**Comment by aschiavon91** [comment]
@trombik seems to be working pretty well now, I left it running for 10/15 minutes and no errors occurred

**Comment by aschiavon91** [comment]
thank you so much, @UncleRus and @trombik!

**Pull request merged**
