### PR TITLE
fix: lsm303 ODR names and non-static scale arrays

### PR DESCRIPTION
**Pull request by QB4-dev**
I have fixed ODR enum names and removed static specifier conversion arrays

### CODE REVIEW

**Comment by UncleRus** [comment]
> removed static specifier conversion arrays

Why?

**Comment by QB4-dev** [comment]
Previously I have kept them as global variables outside of functions so added static for not being visible outside .c files, and forgot to remove static when pasted inside the functions.

All calculations using this arrays are done inside the functions so I think it is OK to keep them on stack with const specifier

Tell me if I am wrong, driver still works fine

**Comment by UncleRus** [comment]
And you don't need to define module-level static constants if you don't want to pollute the module-level namespace. Just declare them as static constants directly in the function (as it is done now) and then these constants will have all the properties declared at the module level, but they will be visible only from the function itself.

```C
static const int module_level_decl = 0;

void func()
{
    static const int func_level_decl = 0;  // same properties as module_level_decl, but visible only in func()
}
```

**Comment by QB4-dev** [comment]
It seems that `const` is enough to place array not on stack:

https://godbolt.org/z/337M3rzvP

See assembly output when `static` is removed, and then remove `const` - then array will be allocated on stack

**Comment by QB4-dev** [comment]
> Cool service, BTW. Thanks!

You are welcome. 
Added `static` specifier back

**Comment by UncleRus** [comment]
Thank you!

**Pull request merged**
