### PR TITLE
meta: move all meta tools to subdirectory

### PR DESCRIPTION
**Pull request by UncleRus**
I suppose it would be better to move the metadata toolkit to a separate subdirectory

### CODE REVIEW

**Comment by UncleRus** [comment]
@trombik Sakurai-san, I need your help.

**Comment by trombik** [comment]
@UncleRus it looks to me that your motivation is to tidy up the top directory, right?
some files, such as `group.rb`, should not belong to `spec` directory, actually. i'll propose a better solution.

**Comment by UncleRus** [comment]
>  it looks to me that your motivation is to tidy up the top directory, right?
Yes, that's right.

**Comment by UncleRus** [comment]
> i'll propose a better solution.

Should I close this PR?

**Comment by trombik** [comment]
let me see. maybe, mark as "draft"?

**Comment by trombik** [comment]
@UncleRus `Gemfile` and `Gemfile.lock` should be in the root of the repository because the location of `Gemfile` determines where the gems are available. for example, when `Gemfile` is under `devtools`, gems and their executable files, such as `rspec`, are available only in `devtools` and its sub-directories. this is not very intuitive because users expect a same command to work regardless of the working directory. other files may be anywhere in the repository, but almost all projects keep `Gemfile` (or other similar files, such as `package.json`, `Pipfile` or `tox.ini`). that's a bit of annoyance, but necessary cost.

is it okay to keep `Gemfile` and `Gemfile.lock` in the root of the repository?

**Comment by UncleRus** [comment]
@trombik Yes, it'll do.

**Pull request closed without merging**
