### PR TITLE
feature: Driver for SCD4x CO2 sensor

### PR DESCRIPTION
**Pull request by UncleRus**
As requested in #204.
@SERIDJ I don't have device, so I need help in writing example and testing.

### CODE REVIEW

**Comment by SERIDJ** [comment]
@UncleRus  hi , of course tell me how i can help u, i have development board ?

**Comment by UncleRus** [comment]
1. You need to write a simple program, an example of using the driver. You can see exactly how in the existing examples. The commit with the written example needs to be pushed into this branch.
2. Run the written example and check if it works correctly.

**Comment by SERIDJ** [comment]
@UncleRus  oky i will try to do that, i found this library : https://github.com/Sensirion/embedded-i2c-scd4x 
but there is a loot of fonction  " TODO:IMPLEMENT "" 
image

i will try to impliment them if i can

**Comment by UncleRus** [comment]
It seems that you do not understand my request very well. What does the ready-made library from Sensirion have to do with it?
This PR **already** has a ready-made library based on `i2cdev` and all that is required of you is just to write a short program that uses it and thus check it.

**Comment by UncleRus** [comment]
And I implore you: please learn how to use markdown on github. Don't post screenshots here.

**Comment by UncleRus** [comment]
Ok, I added an example myself. Please run it on esp32 with a connected SCD4x.
Connect SDA to GPIO16 and SCL to GPIO17.
Please check if there are pull-up resistors on the SCD4x devboard. If no (which is unlikely), tell me and I'll change example for you.

**Comment by SERIDJ** [comment]
ah oky, i didnt found library of SCD4x in  esp-idf-lib/components/ that why i tried to do that, 
i will test it right now and i will back u result. Thanks for help

**Comment by SERIDJ** [comment]
Test done, it work well for now : 

I (10570) scd4x-example: CO2: 1286 ppm
I (10570) scd4x-example: Temperature: 28.35 Â°C
I (10570) scd4x-example: Humidity: 26.81 %
I (15580) scd4x-example: CO2: 1265 ppm
I (15580) scd4x-example: Temperature: 27.86 Â°C
I (15580) scd4x-example: Humidity: 27.46 %
I (20590) scd4x-example: CO2: 1231 ppm
I (20590) scd4x-example: Temperature: 27.38 Â°C
I (20590) scd4x-example: Humidity: 28.07 %
I (25600) scd4x-example: CO2: 1218 ppm
I (25600) scd4x-example: Temperature: 26.96 Â°C
I (25600) scd4x-example: Humidity: 28.59 %


just i  should add pull-up resistors on the SCD4x devboard   !!

**Comment by UncleRus** [comment]
@SERIDJ Thank you!
Merged.

**Comment by SERIDJ** [comment]
@UncleRus  thank u for u, just another think about Kconfig file its for "SHT3X demo" u should change it :)

**Comment by UncleRus** [comment]
Yep, the power of copy-paste.

**Pull request merged**
