### PR TITLE
sts3x driver implementation

### PR DESCRIPTION
**Pull request by slimcdk**
New pull request for sts3x implementation #531

### CODE REVIEW

**Comment by UncleRus** [comment]
Default example for sts3x (`/examples/sts3x/default`) is required.

**Comment by UncleRus** [comment]
At the moment, our CI is broken for versions esp-idf v4.x and esp8266. We'll have to wait until we fix it, but there's one thing you can fix right now: the README.md file must be generated as described in CONTRIBUTING.md. If you change it manually, the "Metadata" check will fail.

**Comment by slimcdk** [comment]
That explains it. README should be alright. Didn't have ruby / bundler installed, so entered it manually, but have since installed bundler and it didn't alter the contents.

I'm done fixing stuff, so should be ready for review now.

**Comment by UncleRus** [comment]
Well, great PR!

Will merge it as soon as we fix the CI and restart the checks :)

**Pull request merged**
